Move two tutorials from `aiida-core` to SINTEF appendices
aiidateam/aiida-tutorials pull request #169
Opened 2019-09-30 14:33 UTC by sphuber

Two pages are added to the appendix of SINTEF that are in depth
tutorials about the `StructureData` and `UpfData` class and how to work
with them. These are moved from the `aiida-core` documentation as they
are too plugin specific for `aiida-core`.

2019-09-30 15:29 UTC, ltalirz commented
@yakutovicha Since I already saw the "tutorial_india"  branch, please note that there are a number of updates in the Sintef tutorial with respect to the May tutorial that make sense to keep migrating forward.

2019-09-30 15:33 UTC, sphuber commented
There is one problem with this PR. Since the pages I am adding contain references to `aiida-core` resources, such as the `StructureData` class, the build fails because it warns that it cannot find these. I think it is possible to reference across packages using intersphinx. Have you ever used this @ltalirz ?

2019-09-30 15:35 UTC, ltalirz requested changes
thanks @sphuber !
just a few modifications of the references (didn't check whether it compiles).

otherwise good to go

2019-09-30 15:35 UTC, ltalirz commented on docs/pages/2019_SINTEF/sections/verdi_shell.rst
> +A more in depth tutorial can be found in :ref:`this appendix<appendix_structure_data>`.
```suggestion
A more in depth tutorial can be found in :ref:`this appendix<2019_sintef_appendix_structure_data>`.
```

2019-09-30 15:35 UTC, ltalirz commented on docs/pages/2019_SINTEF/sections/verdi_shell.rst
> +A more in depth tutorial about working with `UpfData` nodes and pseudo potenial families can be found in :ref:`this appendix<appendix_upf_data>`.
```suggestion
A more in depth tutorial about working with `UpfData` nodes and pseudo potenial families can be found in :ref:`this appendix<2019_sintef_appendix_upf_data>`.
```

2019-09-30 15:35 UTC, ltalirz commented on docs/pages/2019_SINTEF/sections/appendix_structure_data.rst
> +.. _appendix_structure_data:
```suggestion
.. _2019_sintef_appendix_structure_data:
```

2019-09-30 15:35 UTC, ltalirz commented on docs/pages/2019_SINTEF/sections/appendix_upf_data.rst
> +.. _appendix_upf_data:
```suggestion
.. _2019_sintef_appendix_upf_data:
```

2019-09-30 16:38 UTC, ltalirz commented
> I think it is possible to reference across packages using intersphinx. Have you ever used this @ltalirz ?

Indeed, I think one can do this.

I've never tried, but I think you can try adding something like this to the `conf.py`:
```python
extensions = [
    'sphinx.ext.intersphinx',
]

intersphinx_mapping = {
    'aiida':  ('https://aiida-core.readthedocs.io/en/latest/', None),
}
```

2019-10-01 07:29 UTC, sphuber commented
Got intersphinx working and adapted the link references you requested. Should be good to go @ltalirz

2019-10-05 11:10 UTC, merged