add structurdata/upfdata appendices to mandi
aiidateam/aiida-tutorials pull request #185
Opened 2019-10-05 11:18 UTC by ltalirz

was added to sintef tutorial; now forwarding to mandi

2019-10-05 11:20 UTC, ltalirz commented
@sphuber moved these tutorials over from aiida-core (PR #169 added this, retrospectively, to the sintef tutorial).

This PR adds them also for the Mandi tutorial, so that this actually can be useful and we keep this material going forward.

2019-10-08 18:19 UTC, CasperWA requested changes
Thanks @ltalirz!
I have made some suggested changes, which I will simply commit and then merge this in.

2019-10-08 18:19 UTC, CasperWA commented on docs/pages/2019_IIT_Mandi_India/sections/verdi_shell.rst
> +A more in depth tutorial about working with `UpfData` nodes and pseudo potenial families can be found in :ref:`this appendix<2019_mandi_appendix_upf_data>`.
```suggestion
A more in-depth tutorial about working with ``UpfData`` nodes and pseudopotential families can be found in :ref:`this appendix<2019_mandi_appendix_upf_data>`.
```

2019-10-08 18:19 UTC, CasperWA commented on docs/pages/2019_IIT_Mandi_India/sections/verdi_shell.rst
> +A more in depth tutorial can be found in :ref:`this appendix<2019_mandi_appendix_structure_data>`.
```suggestion
A more in-depth tutorial can be found in :ref:`this appendix<2019_mandi_appendix_structure_data>`.
```

2019-10-08 18:30 UTC, merged