WIP: Versions info to ones from Quantum Mobile image updated
aiidateam/aiida-tutorials pull request #311
Opened 2021-02-05 12:53 UTC by flavianojs

2021-02-08 14:16 UTC, flavianojs commented
@mbercx do you know why these commits are failing the continuous-integration tests?

2021-02-08 14:42 UTC, mbercx commented
> @mbercx do you know why these commits are failing the continuous-integration tests?

These were already failing from my initial push, it seems. 😅  I just wanted to have a working html build so you could start going through the material. Let me see if I can fix these issues in a separate branch and then you can rebase.

PS: Let me know when the PR is ready for review!

2021-02-08 22:42 UTC, mbercx requested changes
Thanks @flavianojs! Just left some minor comments, mainly re the versioning. I think these will actually match those of the BIGMAP tutorial. I'll test the whole querying section  on the [AiiDAlab demo cluster](https://aiidalab-demo.materialscloud.org/) after this is merged. Tomorrow we can give the whole tutorial one final pass on the actual cluster we'll be using.

2021-02-08 22:42 UTC, mbercx commented on docs/index.rst
> +| python packages | `aiida-core 1.3.0`_, `aiida-quantumespresso 3.0.0`_                                                       |
The package versions probably won't correspond to these. I'm assuming they will still be the same as those from the BIGMAP tutorial.

```suggestion
| python packages | `aiida-core 1.4.3`_, `aiida-quantumespresso 3.2.1`_                                                       |
```

2021-02-08 22:42 UTC, mbercx commented on docs/index.rst
> +| codes           | `Quantum ESPRESSO 6.5`_                                                                                   |
Same here, unfortunately. I left these as XXXX's to fix when the AiiDAlab cluster was up and running. On https://aiidalab-demo.materialscloud.org/ the Quantum ESPRESSO version is still 6.0.

2021-02-08 22:42 UTC, mbercx commented on docs/source/sections/data.rst
> +   Probably requires update.
So you didn't test this section yet, right? 🙃

2021-02-08 22:59 UTC, mbercx commented on docs/source/sections/data.rst
> +   Probably requires update.
Just quickly executed the commands in the section and then ran the whole solution notebook. Seems we have to remove the duplicate groups made with this command:

```console
$ verdi group copy tutorial_lda tutorial/lda/basic
$ verdi group copy tutorial_pbe tutorial/gga/pbe
$ verdi group copy tutorial_pbesol tutorial/gga/pbesol
```

Else the final plot won't work (it expects 3 pseudopotential groups, not 6).

2021-02-09 10:20 UTC, mbercx commented on docs/index.rst
> +| python packages | `aiida-core 1.3.0`_, `aiida-quantumespresso 3.0.0`_                                                       |
Just checked the versions, and these are correct!

2021-02-09 10:49 UTC, merged