minor update for plugin tutorial
aiidateam/aiida-tutorials pull request #367
Opened 2021-06-30 08:30 UTC by ltalirz

2021-06-30 11:37 UTC, mbercx requested changes, later dismissed
All good, thanks Leo! Just two minor comments related to the fact that I changed the `header-text` CSS a bit, so now there is a specific `panel-header-text` class that doesn't have this extra `margin-bottom`.

2021-06-30 11:37 UTC, mbercx commented on docs/sections/plugins/index.rst
>      :header: header-text
```suggestion
    :header: panel-header-text
```

2021-06-30 11:37 UTC, mbercx commented on docs/sections/plugins/index.rst
>      :header: header-text
```suggestion
    :header: panel-header-text
```

2021-07-01 16:16 UTC, ramirezfranciscof approved these changes
LGTM! Thanks @ltalirz and @mbercx !

2021-07-01 16:18 UTC, merged