Add instruction for aiidalab-launch
aiidateam/aiida-tutorials pull request #446
Opened 2022-10-03 13:17 UTC by unkcpz

Since the `aiidalab-widgets-base` migrate to 2.x is not finished, I have to add an instruction to remove it from the default app list.

2022-10-03 14:37 UTC, mbercx requested changes
Thanks @unkcpz! Want to give this a shot first before merging, will try later!

2022-10-03 14:37 UTC, mbercx commented on docs/sections/getting_started/setup.md
> +## Setup using AiiDAlab Launch
This seems like duplication?

2022-10-03 14:39 UTC, unkcpz commented on docs/sections/getting_started/setup.md
> +## Setup using AiiDAlab Launch
That's true, forgot to delete it.

2022-10-03 14:40 UTC, unkcpz commented on docs/sections/getting_started/setup.md
> +## Setup using AiiDAlab Launch
Should be fine now.

2022-10-04 12:44 UTC, unkcpz commented
Update the instruction for setting the `non-sudo` docker user as a mandatory pre-requisites.

2022-10-04 12:49 UTC, mbercx approved these changes
Thanks @unkcpz! Just one nitpicky comment and this is good to merge.

2022-10-04 12:49 UTC, mbercx commented on docs/sections/getting_started/setup.md
> +1. [Install Docker on your workstation or laptop.](https://docs.docker.com/get-docker/) and [Manage Docker as a non-root user](https://docs.docker.com/engine/install/linux-postinstall/)
```suggestion
1. [Install Docker on your workstation or laptop](https://docs.docker.com/get-docker/) and [Manage Docker as a non-root user](https://docs.docker.com/engine/install/linux-postinstall/).
```

2022-10-04 13:04 UTC, unkcpz commented on docs/sections/getting_started/setup.md
> +1. [Install Docker on your workstation or laptop.](https://docs.docker.com/get-docker/) and [Manage Docker as a non-root user](https://docs.docker.com/engine/install/linux-postinstall/)
Thanks for the fix! I just saw the message.

2022-10-04 13:05 UTC, merged