Fixes to Section 3 ("verdi shell").
aiidateam/aiida-tutorials pull request #58
Opened 2019-05-09 17:26 UTC by borellim

Some questions:
* Please confirm that the tutorial will take place under Python 3. If not, or if we are not sure, we should change the instructions for creating a new Jupyter notebook to reflect this.
* We say that `it is recommended (and easier) to use the DataFactory function instead of an explicit import`. To be honest I was never convinced of this, especially now that we limit importable depths in aiida-core to 2 levels: direct imports offer auto-completion in many editors, and this is a huge benefit. Can you try to make the argument more convincing?

Thanks!

2019-05-09 17:43 UTC, sphuber commented
As per your questions:
* Yes the current VM is running python 3
* The reason was and still is (despite, the new module hierarchy import simplification) that it only relies on the plugin name, which should be unchanging. The modules however aren't and even though currently the inner module structure could change and through the exposing to the top, one could still use `aiida.orm` directly, at some point some of the data classes may actually be removed from `aiida-core`, such as `StructureData`. If one uses the `DataFactory` now, the code will continue to work without changes
* Was there still a reference to `ParameterData` anywhere? If not, would this perhaps create more confusion than it clears up?

2019-05-09 17:48 UTC, sphuber requested changes
Looking good, just a few minor changes

2019-05-09 17:48 UTC, sphuber commented on docs/pages/2019_MARVEL_Psik_MaX/sections/verdi_shell.rst
> +``KpointsData`` class. Choose one from the graph of :numref:`aiidagraph`,
The link `aiidagraph` is actually a section link, not the figure. If you want to reference the figure use `fig_graph`

2019-05-09 17:48 UTC, sphuber commented on docs/pages/2019_MARVEL_Psik_MaX/sections/verdi_shell.rst
> +Get the PK and load the input parameters of a calculation in the graph of :numref:`aiidagraph`.
wrong link, see above

2019-05-09 17:48 UTC, sphuber commented on docs/pages/2019_MARVEL_Psik_MaX/sections/verdi_shell.rst
> +Find a structure in the graph of :numref:`aiidagraph` and load it.
idem

2019-05-09 17:48 UTC, sphuber commented on docs/pages/2019_MARVEL_Psik_MaX/sections/verdi_shell.rst
> +Structures in AiiDA are instances of class ``StructureData``: load it in the
instance of *the* class

2019-05-09 17:52 UTC, borellim commented
Thanks a lot for replying.

> at some point some of the data classes may actually be removed from `aiida-core`

Makes sense. So it's "more future-proof" rather than "safer"... no?

> Was there still a reference to ParameterData anywhere? If not, would this perhaps create more confusion than it clears up?

Possibly, but if I was a student and I already knew AiiDA from pre-1.0, I would want to see this change highlighted.
Anyway, I found some references, but I don't know if these pages still need to be rewritten:
```
~/repos/aiida-tutorials/docs/pages/2019_MARVEL_Psik_MaX$ grep -rin ParameterData
sections/appendix_input_validation.rst:49:    parameters = ParameterData(dict=validated_dict)
sections/verdi_shell.rst:167:(formerly called ``ParameterData`` in previous versions of AiiDA).
scripts/equation_of_states.py:50:        ParameterData = DataFactory("parameter")
scripts/equation_of_states.py:53:                'result': ParameterData(dict={'eos_data': eos})
scripts/pressure_convergence.py:16:ParameterData = DataFactory('parameter')
notebooks/querybuilder-template.ipynb:382:    " ParameterData | 2922  \n",
```

2019-05-09 18:04 UTC, sphuber commented
> Makes sense. So it's "more future-proof" rather than "safer"... no?

Yes, that is a better way of putting it. Feel free to adapt the text to say that

> Possibly, but if I was a student and I already knew AiiDA from pre-1.0, I would want to see this change highlighted.

Fair enough, but then shouldn't we also do the same for the many other changes?
There are way too many of those and it would clutter the text.

> Anyway, I found some references, but I don't know if these pages still need to be rewritten:
> 
> ```
> ~/repos/aiida-tutorials/docs/pages/2019_MARVEL_Psik_MaX$ grep -rin ParameterData
> sections/appendix_input_validation.rst:49:    parameters = ParameterData(dict=validated_dict)
> sections/verdi_shell.rst:167:(formerly called ``ParameterData`` in previous versions of AiiDA).
> scripts/equation_of_states.py:50:        ParameterData = DataFactory("parameter")
> scripts/equation_of_states.py:53:                'result': ParameterData(dict={'eos_data': eos})
> scripts/pressure_convergence.py:16:ParameterData = DataFactory('parameter')
> notebooks/querybuilder-template.ipynb:382:    " ParameterData | 2922  \n",
> ```

Those are problems and need to be fixed.

2019-05-09 18:39 UTC, borellim commented
> > Makes sense. So it's "more future-proof" rather than "safer"... no?
> 
> Yes, that is a better way of putting it. Feel free to adapt the text to say that

Done. Please take a look if you like it.

> > Possibly, but if I was a student and I already knew AiiDA from pre-1.0, I would want to see this change highlighted.
> 
> Fair enough, but then shouldn't we also do the same for the many other changes?
> There are way too many of those and it would clutter the text.

Ok, fine. You know better than me how many of these cases there are. I have removed the reference to `ParameterData`.

2019-05-09 21:50 UTC, ltalirz commented
@sphuber I let you do the final review & merge

2019-05-10 06:48 UTC, merged

2019-05-10 06:48 UTC, sphuber commented
Thanks to both